[package]
name = "eks_builder"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11.8"
figment = { version ="0.10.19", features = ["yaml"] }
serde = { version = "1.0.219", features = ["derive"] }